SKILLS = [
    "python", "javascript", "typescript", "java", "c++", "c#", "go", "rust", "php", "ruby",
    "swift", "kotlin", "scala", "r", "matlab", "bash", "shell scripting", "powershell",
    "react", "angular", "vue", "next.js", "nuxt.js", "svelte", "jquery", "bootstrap",
    "tailwind css", "html", "css", "sass", "webpack", "vite", "babel",
    "node.js", "express", "django", "flask", "fastapi", "spring boot", "laravel", "rails",
    "asp.net", "graphql", "rest api", "soap", "grpc",
    "mysql", "postgresql", "mongodb", "redis", "sqlite", "oracle", "cassandra", "dynamodb",
    "elasticsearch", "firebase", "supabase",
    "aws", "azure", "google cloud", "docker", "kubernetes", "terraform", "ansible",
    "jenkins", "github actions", "ci/cd", "linux", "nginx", "apache",
    "git", "github", "gitlab", "bitbucket", "jira", "confluence", "trello",
    "machine learning", "deep learning", "tensorflow", "pytorch", "keras", "scikit-learn",
    "pandas", "numpy", "matplotlib", "data analysis", "data visualization", "tableau",
    "power bi", "nlp", "computer vision", "opencv",
    "agile", "scrum", "kanban", "project management", "product management",
    "communication", "teamwork", "leadership", "problem solving", "critical thinking",
    "time management", "adaptability", "creativity", "attention to detail",
    "unit testing", "integration testing", "jest", "pytest", "selenium", "cypress",
    "tdd", "bdd", "code review", "debugging",
    "microservices", "serverless", "event-driven architecture", "design patterns",
    "solid principles", "clean code", "system design", "api design",
    "jwt", "oauth", "authentication", "authorization", "cybersecurity", "ssl/tls",
    "figma", "adobe xd", "ui/ux", "wireframing", "prototyping",
    "excel", "google sheets", "data entry", "reporting",
    "blockchain", "solidity", "web3", "smart contracts",
    "ios development", "android development", "react native", "flutter",
    "hadoop", "spark", "kafka", "airflow", "etl", "data engineering",
    "devops", "site reliability engineering", "monitoring", "logging",
    "prometheus", "grafana", "datadog", "splunk",
    "salesforce", "sap", "erp", "crm",
    "content management", "seo", "digital marketing", "google analytics",
    "technical writing", "documentation", "research", "analysis",
    "budget management", "stakeholder management", "risk management",
    "sql", "nosql", "database design", "orm", "stored procedures",
    "cloud computing", "virtualization", "networking", "tcp/ip",
]
